<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * InquiryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InquiryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByKeyword($keyword)
    {
        $query = $this->createQueryBuilder('i')
            ->where('i.name LIKE :keyword')
            ->orWhere('i.tel LIKE :keyword')
            ->orWhere('i.email LIKE :keyword')
            ->setParameters([
                ':keyword' => '%' . $keyword . '%'
            ])
            ->getQuery();

        return new ArrayCollection($query->getResult());
    }
}
